sonar.sourceEncoding=UTF-8
sonar.projectKey=abhishekmalvadkar_lms-service-api
sonar.projectName=lms-service-api
sonar.organization=amalvadkar
sonar.host.url=https://sonarcloud.io

sonar.coverage.exclusions=src/main/java/**/Application.*,src/main/java/**/exceptions/**